export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const CHANGE_PRODUCT = "CHANGE_PRODUCT";

export const CONTENT_START = 'CONTENT_START';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAILED = 'CONTENT_FAILED';
